version: "3"

services:
  database_users:
    build: ./database_users
    container_name: database_users
    platform: linux/amd64
    restart: always
    networks:
      - spring_net

  database_devices:
    build: ./database_devices
    container_name: database_devices
    restart: always
    networks:
      - spring_net

  backend_users:
    build: ./backend_users
    image: backend_users
    container_name: backend_users
    platform: linux/amd64
    ports:
      - "8080:8080"
    restart: always
    networks:
      - spring_net
      - frontend_net
    depends_on:
      - database_users

  backend_devices:
    build: ./backend_devices
    container_name: backend_devices
    ports:
      - "8081:8080"
    restart: always
    networks:
      - spring_net
      - frontend_net
    depends_on:
      - database_devices

  frontend:
    build: ./frontend
    image: frontend
    ports:
      - 3000:3000
    networks:
      - frontend_net

  backend_devices_consumer:
    build: ./backend_devices_consumer
    image: backend_devices_consumer
    ports:
      - "8082:8082"
    networks:
      - spring_net

networks:
  spring_net:
  frontend_net:
